info:
  contact: {}
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with a username, email, password, and optional
        avatar file.
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Avatar file (optional)
        in: formData
        name: ava
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: 'message: User created successfully'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 'error: Invalid request'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'error: Internal server error'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Authentication
swagger: "2.0"
